[package]
name = "moxie-native-devtools"
version = "0.1.0"
authors = ["Tiffany Bennett <tiffnixen@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.11"
moxie = "0.7.1"
topo = "0.13.2"

[dependencies.moxie-native]
path = "../"
